services:
  - type: web
    name: django-bookstore
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn bookstore_project.wsgi
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: bookstore_project.settings
      - key: SECRET_KEY
        value: your-super-secret-key
      - key: DEBUG
        value: False
